import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Header } from '~/components/layouts/Layout/Header'
import { Top } from '~/components/pages/Top'
import { Footer } from '~/components/layouts/Layout/Footer'
import { Box } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Tokki</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box>
				{/* <Box bg="gray.50" h="max-full"> */}
				<Top />
				{/* <Box pt={12}>
					<Footer />
				</Box> */}
			</Box>
		</>
	)
}
